<a href="https://colab.research.google.com/github/SalahSharaf/Collaborative_Recommendation_Engine_different_techniques.ipynb/blob/main/Collaborative_Recommendation_Engine_different_techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## first we import basic liberaries

In [3]:
import pandas as pd
import numpy as np
import scipy as sp
from sklearn.metrics.pairwise import cosine_similarity

#### here we install spark 

### making item-based recommender

In [269]:
df=pd.read_csv('/content/user_ratings.csv')
df.tail()

userId  ...                 genres
100831     610  ...        Action|Thriller
100832     610  ...     Action|Crime|Drama
100833     610  ...  Action|Drama|Thriller
100834     610  ...        Horror|Thriller
100835     610  ...                 Horror

[5 rows x 6 columns]

In [270]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   userId     100836 non-null  int64  
 1   movieId    100836 non-null  int64  
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64  
 4   title      100836 non-null  object 
 5   genres     100836 non-null  object 
dtypes: float64(1), int64(3), object(2)
memory usage: 4.6+ MB


In [271]:
df_pivot=df.pivot(index='userId',columns='movieId',values='rating')
df_pivot.head()

movieId  1       2       3       4       ...  193583  193585  193587  193609
userId                                   ...                                
1           4.0     NaN     4.0     NaN  ...     NaN     NaN     NaN     NaN
2           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
3           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
4           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
5           4.0     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN

[5 rows x 9724 columns]

### cleaning and normalizing data

In [69]:
avg_rating=df_pivot.mean(axis=1)

In [70]:
df_pivot_normalized=df_pivot.sub(avg_rating,axis=0)

In [71]:
df_pivot_normalized=df_pivot.fillna(0)

### then we transpose to make it item_based matrix

In [72]:
df_pivot_item=df_pivot_normalized.T
df_pivot_item

userId   1    2    3    4    5    6    7    ...  604  605  606  607  608  609  610
movieId                                     ...                                   
1        4.0  0.0  0.0  0.0  4.0  0.0  4.5  ...  3.0  4.0  2.5  4.0  2.5  3.0  5.0
2        0.0  0.0  0.0  0.0  0.0  4.0  0.0  ...  5.0  3.5  0.0  0.0  2.0  0.0  0.0
3        4.0  0.0  0.0  0.0  0.0  5.0  0.0  ...  0.0  0.0  0.0  0.0  2.0  0.0  0.0
4        0.0  0.0  0.0  0.0  0.0  3.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5        0.0  0.0  0.0  0.0  0.0  5.0  0.0  ...  3.0  0.0  0.0  0.0  0.0  0.0  0.0
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
193581   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
193583   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
193585   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
193587   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
193609   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[9724 rows x 610 columns]

In [73]:
similarity_item=cosine_similarity(df_pivot_item)

In [74]:
similarity_item_df=pd.DataFrame(similarity_item,columns=df_pivot_item.index,index=df_pivot_item.index)

In [75]:
similarity_item_df.head()

movieId    1         2         3         4       ...  193583  193585  193587  193609
movieId                                          ...                                
1        1.000000  0.410562  0.296917  0.035573  ...     0.0     0.0     0.0     0.0
2        0.410562  1.000000  0.282438  0.106415  ...     0.0     0.0     0.0     0.0
3        0.296917  0.282438  1.000000  0.092406  ...     0.0     0.0     0.0     0.0
4        0.035573  0.106415  0.092406  1.000000  ...     0.0     0.0     0.0     0.0
5        0.308762  0.287795  0.417802  0.188376  ...     0.0     0.0     0.0     0.0

[5 rows x 9724 columns]

### lets recommend some movies

In [76]:
def recommend(movie_name):
  # id=df[df['title']==name].movieId.values
  # values=similarity_df.loc[id].values.squeeze()
  # print(values.shape)
  # print(df.title.unique().shape)
  #series=pd.Series(values,index=df.title.unique())
  id=df[df['title']==movie_name].movieId.values[0]
  series=similarity_item_df.loc[id]
  sorted_series=series.sort_values(ascending=False)
  movies=[]
  for id in sorted_series.index.values:
    movies.append(df[df['movieId'] ==id].title.values[0])
  recommended_df=pd.DataFrame(data={'movie name':movies,'recommendation rank':sorted_series.values[0]})
  return recommended_df.head(200)

In [ ]:
recommend('31 (2016)')

### now Knn model to predict similar users pehaviour

In [77]:
similarity_user=cosine_similarity(df_pivot_normalized)

In [78]:
similarity_user_df=pd.DataFrame(similarity_user,columns=df_pivot.index,index=df_pivot.index)

In [79]:
similarity_user_df.head()

userId       1         2         3    ...       608       609       610
userId                                ...                              
1       1.000000  0.027283  0.059720  ...  0.291097  0.093572  0.145321
2       0.027283  1.000000  0.000000  ...  0.046211  0.027565  0.102427
3       0.059720  0.000000  1.000000  ...  0.021128  0.000000  0.032119
4       0.194395  0.003726  0.002251  ...  0.149858  0.032198  0.107683
5       0.129080  0.016614  0.005020  ...  0.135535  0.261232  0.060792

[5 rows x 610 columns]

In [86]:
user_id=610
movie_id=1

In [87]:
series=similarity_user_df.loc[user_id]
ordered_series=series.sort_values(ascending=False)
nearest_neighbors=ordered_series[1:5].index
nearest_neighbors.values

array([249, 298, 274, 380])

In [88]:
nearest_df=df_pivot_normalized.reindex(nearest_neighbors)
nearest_df[movie_id].mean()

3.75

In [124]:
temp_df=df_pivot_normalized.drop(movie_id,axis=1)

In [128]:
target_user_x=temp_df.loc[[user_id]]

In [129]:
target_user_x

movieId  2       3       4       5       ...  193583  193585  193587  193609
userId                                   ...                                
610         0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0

[1 rows x 9723 columns]

In [130]:
other_users_y=df_pivot_normalized[movie_id]
other_users_y

userId
1      4.0
2      0.0
3      0.0
4      0.0
5      4.0
      ... 
606    2.5
607    4.0
608    2.5
609    3.0
610    5.0
Name: 1, Length: 610, dtype: float64

In [132]:
other_users_x=temp_df[other_users_y.notnull()]
other_users_x

movieId  2       3       4       5       ...  193583  193585  193587  193609
userId                                   ...                                
1           0.0     4.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
2           0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
3           0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
4           0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
5           0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
...         ...     ...     ...     ...  ...     ...     ...     ...     ...
606         0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
607         0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
608         2.0     2.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
609         0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
610         0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0

[610 rows x 9723 columns]

### using knn regressor

In [140]:
from sklearn.neighbors import KNeighborsRegressor
user_knn_r = KNeighborsRegressor(metric='cosine', n_neighbors=3)
user_knn_r.fit(other_users_x, other_users_y)
user_user_pred = user_knn_r.predict(target_user_x)
user_user_pred

array([3.66666667])

### now we will try matrix factorization to test weither it's better 

### first approach we will use SVD function 

In [150]:
sparcity= (df_pivot.isna().sum().sum()/df_pivot.size)

In [151]:
sparcity

0.9830003169443864

In [206]:
df_pivot.shape

(610, 9724)

In [295]:
from scipy.sparse.linalg import svds
df_pivot_centered=df_pivot.sub(avg_rating,axis=0)
df_pivot_centered.fillna(0,inplace=True)
U, sigma, Vt = svds(df_pivot_centered,20)
print(sigma.shape)
print(U.shape)
print(Vt.shape)

(20,)
(610, 20)
(20, 9724)


In [296]:
sigma=np.diag(sigma)
print(sigma.shape)

(20, 20)


In [297]:
from pandas.core.resample import f
full_matrix=np.dot(np.dot(U,sigma),Vt)
print(full_matrix.shape)
print(full_matrix[0:4,0:4])

(610, 9724)
[[ 5.30488705e-02 -7.83127284e-03 -1.37263696e-02 -3.26936578e-02]
 [-8.68594984e-03  1.36810790e-03 -1.10665919e-02  2.93605201e-04]
 [-5.54103290e-02  1.41727179e-02 -2.11037807e-02 -4.42452183e-05]
 [ 2.12942295e-01  4.14654485e-02  3.72616878e-02 -1.89160237e-02]]


In [298]:
calculated_ratings=full_matrix+avg_rating.values.reshape(-1,1)
calculated_ratings[0:4,0:4]

array([[4.41942818, 4.35854804, 4.35265294, 4.33368565],
       [3.93958991, 3.94964397, 3.93720927, 3.94856947],
       [2.38048711, 2.45007015, 2.41479366, 2.43585319],
       [3.76849785, 3.597021  , 3.59281724, 3.53663953]])

In [299]:
calculated_ratings.shape

(610, 9724)

In [300]:
df_pivot_svds=pd.DataFrame(calculated_ratings,columns=df_pivot.columns,index=df_pivot.index)

In [301]:
from sklearn.metrics import mean_squared_error
mean_squared_error(df_pivot.fillna(0).values,df_pivot_svds.values,squared=False)

3.660068953536393

### now will use pyspark ALS model

In [142]:
!pip install pyspark

     |████████████████████████████████| 281.4 MB 35 kB/s 
     |████████████████████████████████| 198 kB 49.5 MB/s 
  Created wheel for pyspark: filename=pyspark-3.2.1-py2.py3-none-any.whl size=281853642 sha256=a116d3b598dfcaf6c008004bc6e635356eb031e7242cd5935db3ae0aac1eaf97
  Stored in directory: /root/.cache/pip/wheels/9f/f5/07/7cd8017084dce4e93e84e92efd1e1d5334db05f2e83bcef74f
Successfully built pyspark


In [303]:
import pyspark
sc=pyspark.SparkContext()
sc.setCheckpointDir('check_point')
spark=pyspark.sql.SparkSession(sc)

In [304]:
df_rating=spark.read.csv('/content/user_ratings.csv',header=True,inferSchema=True)

In [305]:
df_rating.show()

+------+-------+------+----------+----------------+--------------------+
|userId|movieId|rating| timestamp|           title|              genres|
+------+-------+------+----------+----------------+--------------------+
|     1|      1|   4.0| 964982703|Toy Story (1995)|Adventure|Animati...|
|     5|      1|   4.0| 847434962|Toy Story (1995)|Adventure|Animati...|
|     7|      1|   4.5|1106635946|Toy Story (1995)|Adventure|Animati...|
|    15|      1|   2.5|1510577970|Toy Story (1995)|Adventure|Animati...|
|    17|      1|   4.5|1305696483|Toy Story (1995)|Adventure|Animati...|
|    18|      1|   3.5|1455209816|Toy Story (1995)|Adventure|Animati...|
|    19|      1|   4.0| 965705637|Toy Story (1995)|Adventure|Animati...|
|    21|      1|   3.5|1407618878|Toy Story (1995)|Adventure|Animati...|
|    27|      1|   3.0| 962685262|Toy Story (1995)|Adventure|Animati...|
|    31|      1|   5.0| 850466616|Toy Story (1995)|Adventure|Animati...|
|    32|      1|   3.0| 856736119|Toy Story (1995)|

In [313]:
df_rating.printSchema()
train,test=df_rating.randomSplit([0.8,0.2],seed=42)
print(train.count())
print(test.count())

root
 |-- userId: integer (nullable = true)
 |-- movieId: integer (nullable = true)
 |-- rating: double (nullable = true)
 |-- timestamp: integer (nullable = true)
 |-- title: string (nullable = true)
 |-- genres: string (nullable = true)

80596
20240


In [315]:
from pyspark.ml.recommendation import ALS
als=ALS(rank=25,regParam=0.1,maxIter=30,ratingCol='rating',itemCol='movieId',userCol='userId')

In [316]:
model=als.fit(train)

In [340]:
prediction=model.transform(test)
prediction=prediction.dropna()
prediction.count()

19447

In [341]:
from pyspark.ml.evaluation import RegressionEvaluator
evaluator=RegressionEvaluator(metricName='rmse',labelCol='rating',predictionCol='prediction')
evaluator.evaluate(prediction)

0.8750680943249141

### it's a way more better than svds 

### here are all ways to recommend to user and the best techniques can be really measured only by user impressions and real behavior 

## Thanks :D